### ISSUE TITLE
Tutorials -  How to communicate with beacon?

### ISSUE THREAD

**Issue by rishabh-khurana** [bluecats/bluecats-documentation#1]
Hi,

My team and I have been trying to integrate the android sdk for bluecats beacon with an android app that we developed. However, I am not sure if we did the integration properly and how to work with sdk, I've been scrolling through the docs on github but unfortunately I wasn't able to find anything that shows the how to communicate with the beacon.

![Screenshot from 2020-04-12 01-38-54](https://user-images.githubusercontent.com/25672349/79048166-834f3e00-7c5e-11ea-8661-bcb301815629.png)

Here is the link to our github repo - 

https://github.com/rishabh-khurana/ioT-BankingApp

I need to use the sdk code in the SelectService.kt file.

https://github.com/rishabh-khurana/ioT-BankingApp/blob/master/app/src/main/java/com/example/bankassist/SelectService.kt

Here's what I want to do inside the formButton.setOnClickListener code block - 

-Send a recurring 'ping' to the beacon.
-call a function (SwitchToDisplayDetails()) when I receive a 'ping' back from the beacon.

Could you please suggest the correct way to achieve this? Please let me know if you need any further details on our implementation.

Thanks,
Rishabh

**Comment by damoclarke** [comment]
Hi Rishabh. 
Have you had a look through the documentation here? https://developer.bluecats.com/documentation/libraries/mobile-SDK-Home

and there is also a sample implementation you can take a look at here:
https://github.com/bluecats/bluecats-scratchingpost-android

Let us know if either of those help you get started.

cheers,
Damien

**Comment by rishabh-khurana** [comment]
Yes I got the correct links, apparently, we don't need to use bluecats sdk for beacon integration, everything we need to interact with beacon in eddystone UID mode can be found in the altbeacon library [AltBeacon](https://altbeacon.github.io/android-beacon-library/documentation.htmll)
